* Slides
** Slide 1
 - Good morning, my name is N. Vianello and I am a physisicist working at Consorzio RFX, Padova
 - In order to introduce you my personal research background I decided to start from what
   have been indicated as the twelve top operation risks which
   according to ITER Research Plans should be addressed by the world-wide fusion community.
   I believe all of you are familiar with this list so I will not go
   through each of them. What I would like to underline, since the
   beginning is that my personal research interests fit very well with
   at least 4 of these points here underlined.
   
** Slide 2
 - As I told I'm a physicists involved in fusion plasma science since
   my Ms.Sci. thesis in 1999.
 - My personal research interests can be summarized into three main macro-areas
   + Flow and turbulence induced transport facing problems which can
     be of some interests for points 2 and 7 of the previous lists
   + Emerging of electromagnetic coherent structures and filaments,
     which again is a scientific topic which can be suited for points
     2 and 7
   + 3D physics and helical plasmas which face problems related to all
     the points highlighted

** Slide 3
 - Concerning the first topic, Flows & Turbulence induced transport
   the main results may be summarized as follow:
   + I've been working on momentum flux generation due to off-diagonal
     terms of the stress tensor in Reversed Field Pinches, including
     the role of Reynolds stress, Maxwell stress and non-linear
     momentum flux. I've proved that beside the high level of magnetic
     fluctuations observed in RFPs, edge flow is primarly due to
     the reynolds stress component
   + I've been actively involved in experiment for sheared flow
     modification through edge biasing, revealing the positive effects
     on plasma transport with a change of relative phase between
     density and potential fluctuations, not homogeneous in the
     perpendicular k numer

** Slide 4
 - For a long time I've been involved in the characterization,
   modeling and comprehension of blobs. Starting from the
   perpendicular plane and completely characterize their features in
   the perpendicular plane including pressure, temperature and potential
 - And determining their role in the anomalous diffusion observed at
   the edge of RFPs. In particular besides their convective motion
   towards the external part of the plasmas these structures
   contribute to the diffusion through the cohalecence and merging

** Slide 5 and 6
 - Besides the characterization in the perpendicular plane I've
   focused on the parallel dynamics of these structures.  In
   particular I've developed the diagnostic and coordinated the
   activities which provide the first direct experimental measurements
   of the parallel current and the parallel vorticity associated to a
   plasma blob in a fusion relevant plasma
 - The competences developed on the RFP experiment RFX-mod have been
   applied also to other configurations in order to obtain information
   on the parallel current associated to plasma filaments also in
   other devices
 - In particular a similar diagnostic, constititued of a miniaturized
   pick-up coil has been used on ASDEX-Upgrade tokamak, and through
   the investigation of the magnetic signatures in all the three
   components associated to a type-I ELM filaments it has been
   possible to infer the first direct measurement of parallel current
   associated to single filament, proving that ELMs actually convect a
   certain amount of current in the SOL
 - I've also been actively involved in the measurement in a small
   plasma device for turbulence studies, the simple magnetized torus
   TORPEX, providing the first direct 2D measurements of parallel
   current associated to a resistive-interchange induced plasma blob
 - Final collaboration on the topics of filaments has been established
   with the spanish stellarator TJ-II collaborating with
   C. Hidalgo. On TJ-II I've collaborated in the design of the a
   suitable diagnostic for the contemperanoeus measurements of plasma
   vorticity and parallel current. This tool have been used in ICRH
   and NBI plasmas at different values of beta both providing
   measurements of current filaments associated to plasma blob in the
   confined region. Furthermore the same tool offer the possibility to
   establish the role of Maxwell stress in driving momentum and its
   variation in the location of resonances
 - I have also active collaboration with a chinese team working on
   type-III ELMs in China
 - I believe that these overview on this particular subject prove the
   intense international collaborations established 
   
** Slide 7
 - The last scientific topics which I've been actively involved in si
   the 3D physics associated to helical plasmas
 - I think all of you are aware of the topological transition observed
   in high current regimes in RFPs, which exhibits an helical core
   surrounded by an almost quasi-simmetric boundary
 - This new topological regimes is characterized by the appearence of
   an internal trasnport barrier whose location coincides with a local
   maxima of the q value, in analogy to the tokamak ITB
 - The small residual helical ripple at the edge (order of 1 % ot the
   total field) is sufficient to modulate differently the ion-elecron
   escape and consequently an ambipolar electric field, and
   corresponding E\times B flow builds up. This flow exhibits the same
   modulation as the dominant mode
 - In an analogous way in high density regimes the mode spectrum is
   dominated by an (m,n) = (0,1) perturbation. as a consequenque also
   the flow is modulated with the same periodicity with a region of
   flow inversion. This is the cause of the appearence of an highly
   radiative zone of accumulation which is found to coincide with the
   X point of the (0,1) mode. This experimental observation can be
   coincilied with recent theories of highly radiative magnetici
   island proposed by Gates and Delgado, although they erroneously
   does not take into account the ambipolar electric field response

** Slide 8
 - As far as my JET activities is concerned I must admit I have a
   relative experience on JET. Nevertheless I start to collaborate on
   two different topics
   + The observation of toroidal braking in EFCC experiments, trying
     to determine the amount of braking from magnetic measurements and
     comparing diferent dosing rate and also as a general view trying
     to observe differences with CW
   + Divertor oscillations and M-Mode. ICRH plasmas and partially NBI
     heated plasma exhibits oscillations with inner-outer divertor out
     of phase which for ICRH are precursor of the M-mode an n=0 mode
     characterized by high density gradient at the pedestal but lower
     temperature. A sort of complementary with respect to the I-mode
     observed in Alcator C-mod

** Slide 9
 - Concerning my coordination activity I had experience both in my
   home laboratory and in the framework of EFDA TTG.
 - As far as RFX-mod is concerned, RFX-mod experimental programs is
   coordianated by task force Leader which cohaudivates the Scientific coordinators
 - The objectives of scientific activities are determined on the basis
   of experimental proposal (around 100 for year) and the time machine
   is granted on the basis of scientific motivation taking into
   account machine condition including wall condition and eventual
   plant failure
 - For RFX-mod I've served as Task Force Leader for two years for two
   different, but somehow related task forces

** Slide 10
- Furthermore in 2011 I've been appointed as coordinator of the
  working group 3D field effects in edge and SOL and diagnostic
  development under EFDA transport topical group.
- As duties I've to monitor and coordinate activities proposed on the
  topic and coming from 11 different European Association, stimulating
  discussion through remote partecipation and reporting the activities
  to the STAC commitee
- I'm presently in the programme commitee for the forthcoming 17th
  joint EU-US TTF meeting, as chairman for the session on Edge and SOL
  turbulence and transport

** Slide 11
 - As a final step I've been asked to provide a personal opinion on
   the view of the task force and consequently, starting from the
   Draft Programme for the 2013 campaign, I've tried to individuate
   which are, according to me the main physical issues at least on the
   part which pertains to my personal competences
   + On the headline 2.2, assess plasma scenario with regards to power
     loads and their mitigation and control I think it's foundamental
     to finalize the characterization of the ELMs in the ILW, which
     appear different as slower, and somehow a little less severe. In
     the framework of the peeling-balloning stability it could be
     deteremine if the new wall determines different pressure/current
     profile thus moving JET in a different plane of the stability diagram.
   + Related to this is the comprehension of the effects of RMP, on
     these new ELMs. In particular efforts should be devoted to the
     comprhenesion of the ambipolar response to the perturbation which
     could change in dependence of the collisionality and try to
     understand if this difference is related somehow to the different
     ELM mitigation/suppression effects and collisionality
   + It should also be tested if the newly proposed theory of
     radiative magnetic island, eventually with the inclusion of
     aforemention ambipolar response has really something to do with
     the density Limit and if eventually this can be actively modified
     (edge power deposition for example) as ITER is supposed to
     routinely operate around the greenwald fraction
 - As far as Confinement, pedestal and ELM physics is concerned
   efforts should be devoted to finalize the characterization of the
   new pedestal found in ILW. Why it's generally cooler, and if this
   is related to different or just enhanced loss mechanism. If this is
   the case effort should be devoted to those diagnostic which could
   provide an insight on pedestal dynamics (i.e correlation
   reflectometry for example)
 - If the pedestal is really the result of a balance between flow and
   turbulence what is eventually different
 - I also think that as done recently in ASDEX some effort should be
   devoted on the GAM/turbulence/flow mechanism, as if really it play
   a role in the LH transition could account for the different/lower
   L-H power threshold observed in ILW
 - Finally also in view of future DT or generally high energy beams,
   the role played by RMP on fast particle should be addressed if
   these two elements will be a key ingredient in future devices.
